version: "3.9"
services:
  etcd:
    image: gcr.io/etcd-development/etcd:v3.5.7
    command: >-
      /usr/local/bin/etcd
      --name s1
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd:2380
      --initial-cluster s1=http://etcd:2380
      --initial-cluster-state new
      --initial-cluster-token tkn
    # No host port exposure needed; services connect via internal DNS (etcd:2379)
    healthcheck:
      test:
        ["CMD", "etcdctl", "endpoint", "health", "--endpoints=http://etcd:2379"]
      interval: 5s
      timeout: 3s
      retries: 10

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ETCD_ENDPOINT=etcd:2379
      - GRID_BIND=0.0.0.0:9100
      # - AUTO_START_LOCAL_WORKERS=true
      # Uncomment to enable Spanner emulator later:
      # - SPANNER_DSN=projects/demo/instances/test/databases/imagefactory
      # - SPANNER_EMULATOR_HOST=spanner:9010
    depends_on:
      etcd:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "9100:9100"
