version: "3.9"
services:
  etcd:
    image: gcr.io/etcd-development/etcd:v3.5.7
    command: >-
      /usr/local/bin/etcd
      --name s1
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd:2380
      --initial-cluster s1=http://etcd:2380
      --initial-cluster-state new
      --initial-cluster-token tkn
    # No host port exposure needed; services connect via internal DNS (etcd:2379)
    healthcheck:
      test:
        ["CMD", "etcdctl", "endpoint", "health", "--endpoints=http://etcd:2379"]
      interval: 5s
      timeout: 3s
      retries: 10

  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator
    ports:
      - "9010:9010" # gRPC
      - "9020:9020" # REST

  spanner-init:
    image: google/cloud-sdk:slim
    depends_on:
      - spanner
    environment:
      - SPANNER_EMULATOR_HOST=spanner:9010
      - CLOUDSDK_CORE_PROJECT=demo
      - CLOUDSDK_API_ENDPOINT_OVERRIDES_SPANNER=http://spanner:9020/
    volumes:
      - ./migrations:/migrations:ro
    entrypoint: ["bash", "-lc"]
    command: >-
      "gcloud config set auth/disable_credentials true &&
       gcloud spanner instances create test --config=emulator-config --description=\"Emu\" --nodes=1 || true &&
       gcloud spanner databases create imagefactory --instance=test --ddl-file=/migrations/spanner.sql || true"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ETCD_ENDPOINT=etcd:2379
      - GRID_BIND=0.0.0.0:9100
      - SPANNER_DSN=projects/demo/instances/test/databases/imagefactory
      - SPANNER_EMULATOR_HOST=spanner:9010
    depends_on:
      etcd:
        condition: service_healthy
      spanner:
        condition: service_started
      spanner-init:
        condition: service_started
    ports:
      - "8080:8080"
      - "9100:9100"

  worker2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ETCD_ENDPOINT=etcd:2379
      - GRID_BIND=0.0.0.0:0
    depends_on:
      etcd:
        condition: service_healthy
      spanner:
        condition: service_started
